### ISSUE TITLE
No font selection for la-dev

### ISSUE THREAD

**Issue by ThreeSevenths** [icons8/line-awesome#38]
Hi I'm using the CSS files from Line awesome, and went to use the la-dev icon today, only to find a sqaure. I can't determine how this isn't working from the scss files, but I had to manually add

```css
.la.la-dev {
    font-family: 'Line Awesome Brands';
    font-weight: 400;
}
```

to the line-awesome.css file to fix the issue. I would've sent a PR over if I knew how to fix it 🤷‍♂️
