### ISSUE TITLE
Version 1.3.0 that's on npm has different font-size on _larger.scss

### ISSUE THREAD

**Issue by jpsantos7** [icons8/line-awesome#62]
https://github.com/icons8/line-awesome/blob/768018587ea2170ccafe5e13201388ae820db563/dist/line-awesome/scss/_larger.scss#L8

The version that's on npm (1.3.0) has the following:
```SCSS
.#{$la-css-prefix}-xs { font-size: 0.75em; }
.#{$la-css-prefix}-2x { font-size: 1em; }
.#{$la-css-prefix}-2x { font-size: 2em; }
.#{$la-css-prefix}-3x { font-size: 3em; }
```

Also the `$la-font-size-base` is not used anywhere is it? I was trying to set another base size.

btw, great work guys!
